version: "3"
services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: "unless-stopped"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "./fail2ban-data:/data"
      - "/var/log:/var/log:ro"
      - "/var/lib/docker/containers/:/container-logs/:ro"
    environment:
      TZ: "Asia/Taipei"
      F2B_LOG_TARGET: "STDOUT"
      F2B_LOG_LEVEL: "INFO"
      F2B_DB_PURGE_AGE: "1d"
      F2B_MAX_RETRY: "3"
      F2B_ACTION: "%(action_mwl)s"
      F2B_IPTABLES_CHAIN: "DOCKER-USER"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"